import Head from "next/head";
import styles from "../styles/Home.module.css";

type Props = {
  title: string;
};

export default function Home({ title = "Home React" }: Props) {
  return (
    <div className={styles.container}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem vindo ao <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </div>
  );
}
